/* =====================================================================
   Mesa de Ayuda ASSE - IntegradoC
   Script 001: esquema de base de datos (PostgreSQL 14 o superior)

   Se aplica automáticamente de dos maneras (las dos son seguras de
   combinar, porque el script queda registrado en VersionEsquema):
   - Con Docker: el contenedor de PostgreSQL lo ejecuta la primera vez
     que crea la base (carpeta /docker-entrypoint-initdb.d).
   - Sin Docker: la aplicación lo ejecuta al iniciar si todavía no
     figura en la tabla VersionEsquema.
   También puede ejecutarse a mano con psql sobre una base vacía.

   Convenciones:
   - Todas las fechas se guardan en hora local de Uruguay
     (America/Montevideo), tipo TIMESTAMP(0) sin zona horaria.
   - Los catálogos nunca se borran: se desactivan (Activo = FALSE) para
     no romper el historial.
   - Las solicitudes no se borran físicamente: EliminadoEn/EliminadoPorId.
   - Los nombres se comparan sin distinguir mayúsculas (como la
     intercalación Modern_Spanish_CI_AS de la versión SQL Server): los
     índices únicos de nombres usan lower(...).
   ===================================================================== */

/* ---------------------------------------------------------------------
   Control de versiones del esquema (lo usa también la aplicación)
   --------------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS VersionEsquema (
    Version    INTEGER      NOT NULL CONSTRAINT PK_VersionEsquema PRIMARY KEY,
    Nombre     VARCHAR(200) NOT NULL,
    AplicadaEn TIMESTAMP(0) NOT NULL
);

/* ---------------------------------------------------------------------
   Búsquedas sin tildes ni mayúsculas
   (reemplaza a COLLATE Latin1_General_CI_AI de SQL Server)
   --------------------------------------------------------------------- */
CREATE EXTENSION IF NOT EXISTS unaccent;

-- "Contraseña Ñandú" -> "contrasena nandu"
CREATE OR REPLACE FUNCTION normalizar(texto TEXT)
RETURNS TEXT
LANGUAGE sql
IMMUTABLE STRICT PARALLEL SAFE
AS $$
    SELECT lower(public.unaccent('public.unaccent'::regdictionary, texto))
$$;

/* ---------------------------------------------------------------------
   Catálogos configurables
   --------------------------------------------------------------------- */
CREATE TABLE Responsable (
    Id      INTEGER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_Responsable PRIMARY KEY,
    Nombre  VARCHAR(100) NOT NULL,
    Activo  BOOLEAN      NOT NULL DEFAULT TRUE,
    Orden   INTEGER      NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX UQ_Responsable_Nombre ON Responsable (lower(Nombre));

CREATE TABLE MedioContacto (
    Id             INTEGER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_MedioContacto PRIMARY KEY,
    Nombre         VARCHAR(60) NOT NULL,
    Activo         BOOLEAN     NOT NULL DEFAULT TRUE,
    Orden          INTEGER     NOT NULL DEFAULT 0,
    Predeterminado BOOLEAN     NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX UQ_MedioContacto_Nombre ON MedioContacto (lower(Nombre));

/* Los códigos (AD, FFRRHH, Seg, ...) se guardan tal cual se usan en la mesa.
   Descripcion es opcional y la completa un administrador si lo desea. */
CREATE TABLE TipoSolicitud (
    Id          INTEGER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_TipoSolicitud PRIMARY KEY,
    Codigo      VARCHAR(30)  NOT NULL,
    Descripcion VARCHAR(200) NULL,
    Activo      BOOLEAN      NOT NULL DEFAULT TRUE,
    Orden       INTEGER      NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX UQ_TipoSolicitud_Codigo ON TipoSolicitud (lower(Codigo));

/* EsResuelto = TRUE indica que el estado cierra la solicitud.
   Todo estado con EsResuelto = FALSE se considera "pendiente". */
CREATE TABLE Estado (
    Id             INTEGER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_Estado PRIMARY KEY,
    Nombre         VARCHAR(60) NOT NULL,
    EsResuelto     BOOLEAN     NOT NULL DEFAULT FALSE,
    Color          VARCHAR(20) NULL,
    Activo         BOOLEAN     NOT NULL DEFAULT TRUE,
    Orden          INTEGER     NOT NULL DEFAULT 0,
    Predeterminado BOOLEAN     NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX UQ_Estado_Nombre ON Estado (lower(Nombre));

/* Nivel: 1 = más urgente. Se usa para ordenar. */
CREATE TABLE Prioridad (
    Id             INTEGER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_Prioridad PRIMARY KEY,
    Nombre         VARCHAR(30) NOT NULL,
    Nivel          INTEGER     NOT NULL,
    Activo         BOOLEAN     NOT NULL DEFAULT TRUE,
    Orden          INTEGER     NOT NULL DEFAULT 0,
    Predeterminado BOOLEAN     NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX UQ_Prioridad_Nombre ON Prioridad (lower(Nombre));

CREATE TABLE Oficina (
    Id       INTEGER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_Oficina PRIMARY KEY,
    Nombre   VARCHAR(150) NOT NULL,
    Activo   BOOLEAN      NOT NULL DEFAULT TRUE,
    CreadoEn TIMESTAMP(0) NOT NULL
);
CREATE UNIQUE INDEX UQ_Oficina_Nombre ON Oficina (lower(Nombre));

CREATE TABLE AreaAsse (
    Id     INTEGER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_AreaAsse PRIMARY KEY,
    Nombre VARCHAR(150) NOT NULL,
    Activo BOOLEAN      NOT NULL DEFAULT TRUE,
    Orden  INTEGER      NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX UQ_AreaAsse_Nombre ON AreaAsse (lower(Nombre));

/* ---------------------------------------------------------------------
   Usuarios del sistema
   --------------------------------------------------------------------- */
CREATE TABLE Usuario (
    Id                  INTEGER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_Usuario PRIMARY KEY,
    NombreUsuario       VARCHAR(50)  NOT NULL,
    NombreCompleto      VARCHAR(120) NOT NULL,
    PasswordHash        VARCHAR(200) NOT NULL,
    Rol                 VARCHAR(20)  NOT NULL CONSTRAINT CK_Usuario_Rol CHECK (Rol IN ('ADMIN', 'SOPORTE')),
    ResponsableId       INTEGER      NULL CONSTRAINT FK_Usuario_Responsable REFERENCES Responsable (Id),
    Activo              BOOLEAN      NOT NULL DEFAULT TRUE,
    DebeCambiarPassword BOOLEAN      NOT NULL DEFAULT FALSE,
    -- Cambia al modificar contraseña, rol o estado: invalida las sesiones abiertas.
    SelloSeguridad      UUID         NOT NULL DEFAULT gen_random_uuid(),
    CreadoEn            TIMESTAMP(0) NOT NULL,
    UltimoAcceso        TIMESTAMP(0) NULL
);
CREATE UNIQUE INDEX UQ_Usuario_NombreUsuario ON Usuario (lower(NombreUsuario));

/* ---------------------------------------------------------------------
   Importaciones de Excel (trazabilidad)
   --------------------------------------------------------------------- */
CREATE TABLE Importacion (
    Id                    INTEGER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_Importacion PRIMARY KEY,
    FechaHora             TIMESTAMP(0) NOT NULL,
    UsuarioId             INTEGER      NOT NULL CONSTRAINT FK_Importacion_Usuario REFERENCES Usuario (Id),
    NombreArchivo         VARCHAR(260) NOT NULL,
    HashArchivo           CHAR(64)     NOT NULL,
    FilasLeidas           INTEGER      NOT NULL,
    SolicitudesNuevas     INTEGER      NOT NULL,
    SolicitudesExistentes INTEGER      NOT NULL,
    FilasConError         INTEGER      NOT NULL,
    FilasConAdvertencia   INTEGER      NOT NULL,
    TareasExtraNuevas     INTEGER      NOT NULL
);

/* ---------------------------------------------------------------------
   Numeración de solicitudes.
   Guarda el último ID emitido: un ID nunca se reutiliza, aunque la
   solicitud se elimine. Se usa esta tabla (y no una SEQUENCE) porque la
   importación de Excel conserva los números originales y el próximo
   número tiene que quedar por encima del mayor importado.
   --------------------------------------------------------------------- */
CREATE TABLE Secuencia (
    Nombre      VARCHAR(50) NOT NULL CONSTRAINT PK_Secuencia PRIMARY KEY,
    UltimoValor INTEGER     NOT NULL
);

/* ---------------------------------------------------------------------
   Solicitudes (equivale a cada fila del Excel)
   --------------------------------------------------------------------- */
CREATE TABLE Solicitud (
    Id                  INTEGER      NOT NULL CONSTRAINT PK_Solicitud PRIMARY KEY,  -- asignado desde Secuencia
    FechaIngreso        TIMESTAMP(0) NOT NULL,                                       -- automática, no cambia al editar
    DiaSemana           INTEGER      NOT NULL CONSTRAINT CK_Solicitud_DiaSemana CHECK (DiaSemana BETWEEN 1 AND 7), -- 1 = lunes
    NombreFuncionario   VARCHAR(150) NULL,
    OficinaId           INTEGER      NULL CONSTRAINT FK_Solicitud_Oficina       REFERENCES Oficina (Id),
    MedioContactoId     INTEGER      NULL CONSTRAINT FK_Solicitud_MedioContacto REFERENCES MedioContacto (Id),
    TipoSolicitudId     INTEGER      NULL CONSTRAINT FK_Solicitud_TipoSolicitud REFERENCES TipoSolicitud (Id),
    Descripcion         VARCHAR(500) NULL,
    Observaciones       TEXT         NULL,
    ResponsableId       INTEGER      NULL CONSTRAINT FK_Solicitud_Responsable   REFERENCES Responsable (Id),
    DuracionEstimadaMin INTEGER      NULL CONSTRAINT CK_Solicitud_Duracion CHECK (DuracionEstimadaMin IS NULL OR DuracionEstimadaMin >= 0),
    EstadoId            INTEGER      NULL CONSTRAINT FK_Solicitud_Estado        REFERENCES Estado (Id),
    PrioridadId         INTEGER      NULL CONSTRAINT FK_Solicitud_Prioridad     REFERENCES Prioridad (Id),
    FechaResolucion     TIMESTAMP(0) NULL,   -- se completa al pasar a un estado resuelto
    MinutosResolucion   INTEGER      NULL,   -- minutos entre FechaIngreso y FechaResolucion
    Origen              VARCHAR(20)  NOT NULL CONSTRAINT CK_Solicitud_Origen CHECK (Origen IN ('APP', 'IMPORTACION')),
    ImportacionId       INTEGER      NULL CONSTRAINT FK_Solicitud_Importacion   REFERENCES Importacion (Id),
    FilaExcel           INTEGER      NULL,
    Version             INTEGER      NOT NULL DEFAULT 1,
    CreadoPorId         INTEGER      NULL CONSTRAINT FK_Solicitud_CreadoPor      REFERENCES Usuario (Id),
    CreadoEn            TIMESTAMP(0) NOT NULL,
    ActualizadoPorId    INTEGER      NULL CONSTRAINT FK_Solicitud_ActualizadoPor REFERENCES Usuario (Id),
    ActualizadoEn       TIMESTAMP(0) NOT NULL,
    EliminadoEn         TIMESTAMP(0) NULL,
    EliminadoPorId      INTEGER      NULL CONSTRAINT FK_Solicitud_EliminadoPor   REFERENCES Usuario (Id)
);

CREATE INDEX IX_Solicitud_FechaIngreso    ON Solicitud (FechaIngreso) INCLUDE (EstadoId, ResponsableId, EliminadoEn);
CREATE INDEX IX_Solicitud_EstadoId        ON Solicitud (EstadoId) INCLUDE (FechaIngreso, ResponsableId, EliminadoEn);
CREATE INDEX IX_Solicitud_ResponsableId   ON Solicitud (ResponsableId);
CREATE INDEX IX_Solicitud_OficinaId       ON Solicitud (OficinaId);
CREATE INDEX IX_Solicitud_TipoSolicitudId ON Solicitud (TipoSolicitudId);

/* ---------------------------------------------------------------------
   Historial de cambios de cada solicitud (una fila por campo cambiado)
   --------------------------------------------------------------------- */
CREATE TABLE SolicitudHistorial (
    Id            BIGINT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_SolicitudHistorial PRIMARY KEY,
    SolicitudId   INTEGER       NOT NULL CONSTRAINT FK_SolicitudHistorial_Solicitud REFERENCES Solicitud (Id),
    FechaHora     TIMESTAMP(0)  NOT NULL,
    UsuarioId     INTEGER       NULL CONSTRAINT FK_SolicitudHistorial_Usuario REFERENCES Usuario (Id),
    Accion        VARCHAR(30)   NOT NULL,  -- CREADA, MODIFICADA, ESTADO, RESUELTA, REABIERTA, IMPORTADA, FECHA_CORREGIDA, ELIMINADA
    Campo         VARCHAR(50)   NULL,
    ValorAnterior TEXT          NULL,
    ValorNuevo    TEXT          NULL,
    Detalle       VARCHAR(2000) NULL
);

CREATE INDEX IX_SolicitudHistorial_SolicitudId ON SolicitudHistorial (SolicitudId, Id);

/* ---------------------------------------------------------------------
   Tareas extra (hoja "Detalle tareas extra")
   --------------------------------------------------------------------- */
CREATE TABLE TareaExtra (
    Id               INTEGER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_TareaExtra PRIMARY KEY,
    AreaAsseId       INTEGER       NULL CONSTRAINT FK_TareaExtra_AreaAsse REFERENCES AreaAsse (Id),
    Tarea            VARCHAR(500)  NOT NULL,
    Impacto          TEXT          NULL,
    CargaTrabajo     VARCHAR(1000) NULL,
    Origen           VARCHAR(20)   NOT NULL CONSTRAINT CK_TareaExtra_Origen CHECK (Origen IN ('APP', 'IMPORTACION')),
    ImportacionId    INTEGER       NULL CONSTRAINT FK_TareaExtra_Importacion REFERENCES Importacion (Id),
    CreadoPorId      INTEGER       NULL CONSTRAINT FK_TareaExtra_CreadoPor REFERENCES Usuario (Id),
    CreadoEn         TIMESTAMP(0)  NOT NULL,
    ActualizadoPorId INTEGER       NULL CONSTRAINT FK_TareaExtra_ActualizadoPor REFERENCES Usuario (Id),
    ActualizadoEn    TIMESTAMP(0)  NOT NULL,
    EliminadoEn      TIMESTAMP(0)  NULL,
    EliminadoPorId   INTEGER       NULL CONSTRAINT FK_TareaExtra_EliminadoPor REFERENCES Usuario (Id)
);

/* Integrantes de la mesa implicados en cada tarea (muchos a muchos) */
CREATE TABLE TareaExtraImplicado (
    TareaExtraId  INTEGER NOT NULL CONSTRAINT FK_TareaExtraImplicado_TareaExtra REFERENCES TareaExtra (Id) ON DELETE CASCADE,
    ResponsableId INTEGER NOT NULL CONSTRAINT FK_TareaExtraImplicado_Responsable REFERENCES Responsable (Id),
    CONSTRAINT PK_TareaExtraImplicado PRIMARY KEY (TareaExtraId, ResponsableId)
);

/* ---------------------------------------------------------------------
   Auditoría de acciones administrativas (catálogos, usuarios, tareas)
   --------------------------------------------------------------------- */
CREATE TABLE Auditoria (
    Id        BIGINT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_Auditoria PRIMARY KEY,
    FechaHora TIMESTAMP(0) NOT NULL,
    UsuarioId INTEGER      NULL CONSTRAINT FK_Auditoria_Usuario REFERENCES Usuario (Id),
    Entidad   VARCHAR(50)  NOT NULL,
    EntidadId VARCHAR(50)  NULL,
    Accion    VARCHAR(30)  NOT NULL,
    Detalle   TEXT         NULL
);

CREATE INDEX IX_Auditoria_FechaHora ON Auditoria (FechaHora);

/* ---------------------------------------------------------------------
   Registro de la versión aplicada
   --------------------------------------------------------------------- */
INSERT INTO VersionEsquema (Version, Nombre, AplicadaEn)
VALUES (1, 'esquema', LOCALTIMESTAMP(0))
ON CONFLICT (Version) DO NOTHING;
